cart/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from products import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.product_list),
    url(r'^profiles/', include('accounts.urls', namespace='accounts')),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^cart/', include('shopping_cart.urls', namespace='shopping_cart')),
    url(r'^accounts/', include('allauth.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.conf.urls import url

from products.views import product_list

app_name = 'products'

urlpatterns = [
    url(r'^', product_list, name='product-list')
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<link rel="stylesheet" href="/static/css/style.css" type="text/css">

<div id="page" class="site">

<header id="masthead" class="site-header" role="banner">

		<!-- #main-menu -->
		<nav class="main-navigation" id="main-nav">

		<div id="primary-menu" class="nav-menu menu"><ul aria-expanded="false" class=" nav-menu">
            <li class="page_item page-item-4"><a href="dresses.html">Dresses</a></li>
            <li class="page_item page-item-4"><a href="bottoms.html">Bottom</a></li>
            <li class="page_item page-item-4"><a href="tops.html">Tops</a></li>
            <li class="page_item page-item-4"><a href="accessories.html">Accessories</a></li>
            <li class="page_item page-item-4"><a href="sale.html">Sale</a></li>


</ul>
             <a href="/cart/order-summary" style="margin-left:1000px;margin-top:-30px;"/>
                <img src="/static/images/baseline-shopping_cart-24px.svg" style="margin-top: -37px;margin-left: 1100"/>
           <h1 class="site-title" style="margin-right:1000px; margin-top: -42px;">
					<a href="home.html" rel="home" style="font-size:30px">
						KVet Co.

					</a>
				</h1>
            </div>


		</nav>

<body>
    {% include 'messages.html' %}
    <div class="container">
        {% block content %}{% endblock content %}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

    {% block script %}{% endblock script %}
</body>

    	<footer id="colophon" class="site-footer container" role="contentinfo">

		<div id="footer-social">

		</div>

		<div class="site-info container">
			© 2018
			<a href="http://kvetco.com/">Nicole Tauler</a>
		</div><!-- .site-info -->

	</footer><!-- #colophon -->
</div>

</html>

templates/messages.html
{% if messages %}

 	<style type="text/css">
 		div.messages{
 			background-color: #ff6b6b;
 			color: #f7fff7;
 		}
 		ul.messages{
 			list-style-type: none;
 		}
 	</style>

    <div class='messages'>

    <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{% if "html_safe" in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}</li>
    {% endfor %}
    </ul>

    </div>
{% endif %}

templates/profile.html
{% extends 'base.html' %}

{% block content %}

<table class="table table-hover table-bordered text-center">
      <tr class="text-center">
        <th>Date Ordered</th>
        <th>Reference Code</th>
        <th>Items</th>
        <th>Price</th>
      </tr>
      {% for order in my_orders %}
        <tr>
          <td>{{ order.date_ordered }}</td>
          <td>{{ order.ref_code }}</td>
          <td>
        	{% for item in order.items.all %}
        		{{ item.product.name }}
      		{% endfor %}
      	  </td>
          <td>${{ order.get_cart_total }}</td>

        </tr>
      {% empty %}
        <tr>
          <td colspan= 4> You have no orders.</td>
        </tr>
      {% endfor %}

      <tr>
        <td colspan=4>
          <a href="{% url 'products:product-list' %}" class="btn btn-warning pull-left">
            {% if not order %}Continue Shopping{% else %}Add Items to Cart {% endif %}
          </a> 
        </td>
      </tr>
    </table>

{% endblock content %}