cart/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from products import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.product_list),
    url(r'^profiles/', include('accounts.urls', namespace='accounts')),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^cart/', include('shopping_cart.urls', namespace='shopping_cart')),
    url(r'^accounts/', include('allauth.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.conf.urls import url

from products.views import product_list

app_name = 'products'

urlpatterns = [
    url(r'^', product_list, name='product-list')
]

shopping_cart/urls.py
from django.conf.urls import url

from .views import (
    add_to_cart,
    delete_from_cart,
    order_details,
    checkout,
    update_transaction_records,
    success
)

app_name = 'shopping_cart'

urlpatterns = [
    url(r'^add-to-cart/(?P<item_id>[-\w]+)/$', add_to_cart, name="add_to_cart"),
    url(r'^order-summary/$', order_details, name="order_summary"),
    url(r'^success/$', success, name='purchase_success'),
    url(r'^item/delete/(?P<item_id>[-\w]+)/$', delete_from_cart, name='delete_item'),
    url(r'^checkout/$', checkout, name='checkout'),
    url(r'^update-transaction/(?P<token>[-\w]+)/$', update_transaction_records,
        name='update_records')
]

products/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=120)
    price = models.IntegerField()

    def __str__(self):
        return self.name

products/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

from shopping_cart.models import Order
from .models import Product


def product_list(request):
    object_list = Product.objects.all()
    filtered_orders = Order.objects.filter()
    current_order_products = []
    if filtered_orders.exists():
    	user_order = filtered_orders[0]
    	user_order_items = user_order.items.all()
    	current_order_products = [product.product for product in user_order_items]



    context = {
        'object_list': object_list,
        'current_order_products': current_order_products
    }

    return render(request, "products/product_list.html", context)

products/templates/products/product_list.html
{% extends 'base.html' %}

{% block content %}
 <div class="site-branding container" >

				<h1 class="site-title">
					<a href="http://nicoletauler.com/" rel="home">
						Holiday 2018

					</a>
				</h1>

										<p class="site-description">
							Dress Collection

						</p>


		</div><!-- .site-branding -->


	<div id="content" class="site-content">

	<div id="primary" class="content-area container">



    {{ message }}


    <table class="row">
       <tr>
           <td>
           <img src="https://cdn.tobi.com/product_images/md/1/silver-so-long-side-slit-maxi-dress.jpg" alt="Silver Maxi" width="75"/>

           </td>
           <td>
            <img src="https://cdn.tobi.com/product_images/md/1/black-date-night-pleated-dress.jpg" alt="Black Skater" width="75"/>
           </td>
           <td>
           <img src="https://cdn.tobi.com/product_images/md/1/red-frances-low-back-mini-bodycon-dress.jpg" alt="Red Bodycon" width="75"/>
           </td>
           <td>
           <img src="https://cdn.tobi.com/product_images/md/1/gold-lucille-sequin-bodycon-dress.jpg" alt="Gold Sequin" width="75"/>
           </td>

       </tr>



    {% for object in object_list %}
        <td class="col-sm-3">
            <p>{{ object.name }}</p>
            <p>Price: ${{ object.price }}</p>
            {% if object in user.profile.ebooks.all %}
            <!-- add a button here to see the product -->
            You own this
            {% elif object in current_order_products %}
            <a href="{% url 'shopping_cart:order_summary' %}" class="btn btn-warning">Go to Cart</a>
            {% else %}
            <a href="{% url 'shopping_cart:add_to_cart' object.id %}" class="btn btn-warning">Add to Cart</a>
            {% endif %}
        </td>


    {% endfor %}
    </table>
{% endblock content %}